kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-gke
spec:
  replicas: 1
  selector:
      matchLabels:
          app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: deployed-app
        image: asia-south1-docker.pkg.dev/clowder-403113/clowder-images/test-app:latest
        imagePullPolicy: Always
        ports: 
          - containerPort: 5000
        resources: 
          requests:
            memory: "128Mi"
            cpu: "250m"
            ephemeral-storage: "512Mi"
          limits:
            memory: "512Mi"
            cpu: "500m"
            ephemeral-storage: "512Mi"